name: Android Build

on:
  push:
    branches:
      - main

jobs:
  android-build:
    runs-on: ubuntu-latest
    env:
      DEV_API_URL: ${{ secrets.DEV_API_URL }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3.0.8
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3.0.8
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android apk
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-dev-release.apk
          path: android/app/build/outputs/apk/dev/release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-stag-release.apk
          path: android/app/build/outputs/apk/stag/release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-prod-release.apk
          path: android/app/build/outputs/apk/prod/release/
